version: 2

sources:
  - name: raw
    database: ecommerce_db
    schema: raw
    tables:
      - name: raw_orders
      - name: raw_customers
      - name: raw_order_items
      - name: raw_payments
      - name: raw_products
      - name: raw_reviews
      - name: raw_sellers
      - name: raw_name_translations
    
models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: order_status
        tests:
          - accepted_values:
              values: ['delivered', 'shipped', 'canceled', 'invoiced', 'processing', 'unavailable', 'approved', 'created']

  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        tests:
          - not_null

  - name: stg_payments
    columns:
      - name: order_id
        tests:
          - not_null
      - name: payment_value
        tests:
          - not_null

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_sellers
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null

  - name: stg_reviews
    columns:
      - name: review_id
        tests:
          - not_null
      - name: review_score
        tests:
          - not_null